title: 孤女努力記
description: 晚安．月亮─床邊故事：孤女努力記
time: Mon, 25 Mar 2024 09:12:41 +0000
items:
  - title: 00. 孤女努力記
    size: 940499
    duration: 95
  - title: 01. 流浪的母女
    size: 4489160
    duration: 456
  - title: 02. 無奈的決定
    size: 4174050
    duration: 442
  - title: 03. 醫生的話
    size: 4725407
    duration: 487
  - title: 04. 醫藥費
    size: 3995250
    duration: 427
  - title: 05. 善良的拉魯克
    size: 4590004
    duration: 478
  - title: 06. 再見吧！伯力卡
    size: 4897503
    duration: 518
  - title: 07. 再見了！媽媽
    size: 4173001
    duration: 435
  - title: 08. 離開巴黎
    size: 4405557
    duration: 455
  - title: 09. 挨餓的滋味
    size: 3837056
    duration: 396
  - title: 10. 旅途中的暴風雨
    size: 4644402
    duration: 483
  - title: 11. 樹林裡的奇遇
    size: 4545843
    duration: 463
  - title: 12. 初識蘿莎麗
    size: 3960430
    duration: 410
  - title: 13. 彭達福先生
    size: 4124677
    duration: 431
  - title: 14. 爸爸的故鄉
    size: 4271679
    duration: 450
  - title: 15. 第一次見到祖父
    size: 4148255
    duration: 434
  - title: 16. 展開新生活
    size: 4769978
    duration: 489
  - title: 17. 難以入睡的一夜
    size: 4603756
    duration: 476
  - title: 18. 進入工廠工作
    size: 4144361
    duration: 416
  - title: 19. 女工的領班
    size: 4662832
    duration: 476
  - title: 20. 發生意外
    size: 4281540
    duration: 441
  - title: 21. 慈祥的彭達福先生
    size: 4306476
    duration: 458
  - title: 22. 童話裡的小屋
    size: 4280057
    duration: 442
  - title: 23. 費盡苦心做成的鞋子
    size: 3566898
    duration: 364
  - title: 24. 充實的生活
    size: 4213634
    duration: 427
  - title: 25. 密友來訪
    size: 3761319
    duration: 392
  - title: 26. 成功的宴會
    size: 3300634
    duration: 335
  - title: 27. 充當臨時翻譯
    size: 4593156
    duration: 462
  - title: 28. 意想不到的幸運
    size: 4522801
    duration: 466
  - title: 29. 成為爺爺的翻譯
    size: 4927635
    duration: 495
  - title: 30. 牽著爺爺的手
    size: 4256264
    duration: 438
  - title: 31. 得到賞識
    size: 4374260
    duration: 458
  - title: 32. 爺爺的寵愛
    size: 4526841
    duration: 482
  - title: 33. 成為祖父的秘書
    size: 4449511
    duration: 463
  - title: 34. 蘿莎麗吃了一驚
    size: 4367161
    duration: 454
  - title: 35. 一封神秘的信
    size: 4267020
    duration: 452
  - title: 36. 特多爾的心機
    size: 4445108
    duration: 457
  - title: 37. 信件的內容
    size: 3922095
    duration: 415
  - title: 38. 唯一的知己
    size: 5190414
    duration: 547
  - title: 39. 搬進嚮往已久的家
    size: 4551264
    duration: 484
  - title: 40. 祖父的家
    size: 4631629
    duration: 478
  - title: 41. 看見爸爸的照片
    size: 4145425
    duration: 434
  - title: 42. 懸賞啟事
    size: 4231585
    duration: 446
  - title: 43. 晴天霹靂
    size: 3865379
    duration: 406
  - title: 44. 遲來的喪禮
    size: 3493552
    duration: 361
  - title: 45. 哀悼大火中的罹難者
    size: 3985388
    duration: 433
  - title: 46. 替工人謀福利
    size: 5056582
    duration: 530
  - title: 47. 鎮上的餐廳
    size: 3687760
    duration: 385
  - title: 48. 占卜有了靈驗
    size: 4487609
    duration: 468
  - title: 49. 可愛的孫女
    size: 4170764
    duration: 440
  - title: 50. 玫瑰花蕾般的臉龐
    size: 4656178
    duration: 468
  - title: 51. 驚喜的重逢
    size: 5103831
    duration: 529
  - title: 52. 七千人的掌聲
    size: 5029520
    duration: 530
